openapi: 3.0.2
info:
  title: SwifttDial VAS Bulk and Premium SMS API
  description: Public SMS API documentation
  version: '1.0'
  x-logo:
    url: https://swifttdial.com/wp-content/uploads/2020/04/mobile-logoArtboard-1-300x133.png
  contact:
    name: Customer Support
    url: https://swifttdial.com/contact-us/
    email: tech@swifttdial.com
paths:
  /v1/bulksms/messages:
    post:
      tags:
        - Bulk SMS
      summary: Send Bulk Sms
      description: Send Bulk Promotional or/and Transactional messages
      operationId: Send_Bulk_SMS_v1_bulksms_messages_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkSMSRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Send Bulk Sms V1 Bulksms Messages Post
                type: array
                items:
                  $ref: '#/components/schemas/BulkSMSResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      callbacks:
        delivery_receipt:
          '{$callback_url}':
            post:
              summary: Delivery Receipt
              operationId: delivery_receipt__callback_url__post
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/BulkSMSDeliveryStatusEvent'
              responses:
                '200':
                  description: Successful Response
                  content:
                    application/json:
                      schema: {}
                '422':
                  description: Validation Error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/HTTPValidationError'
      security:
        - X-API-Key: []
  /v1/bulksms/messages/status:
    get:
      tags:
        - Bulk SMS
      summary: Message Status
      description: Check the delivery status of a single/Bulk messages
      operationId: Message_Status_v1_bulksms_messages_status_get
      parameters:
        - required: true
          schema:
            title: Message Ref
            maxLength: 50
            minLength: 3
            type: string
          name: message_ref
          in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - X-API-Key: []
  /v1/premiumsms/subscriptions/start:
    post:
      tags:
        - Premium SMS
      summary: Start Subscriptions
      operationId: Start_Subscriptions_v1_premiumsms_subscriptions_start_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PremiumSMSSubscriptionRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PremiumSMSSubscriptionResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - X-API-Key: []
  /v1/premiumsms/subscriptions/stop:
    post:
      tags:
        - Premium SMS
      summary: Stop Subscriptions
      operationId: Stop_Subscriptions_v1_premiumsms_subscriptions_stop_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PremiumSMSSubscriptionRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PremiumSMSUnSubscriptionResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
        - X-API-Key: []
  /v1/premiumsms/messages:
    post:
      tags:
        - Premium SMS
      summary: Premium Sms Messages
      operationId: Premium_SMS_Messages_v1_premiumsms_messages_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PremiumSMSRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Premium Sms Messages V1 Premiumsms Messages Post
                type: array
                items:
                  $ref: '#/components/schemas/PremiumSMSResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestError'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      callbacks:
        sms_inbound_mo:
          '{$callback_url}':
            post:
              summary: Sms Inbound Mo
              operationId: sms_inbound_mo__callback_url__post
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/MobileOriginatedSMSEvent'
              responses:
                '200':
                  description: Successful Response
                  content:
                    application/json:
                      schema: {}
                '422':
                  description: Validation Error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/HTTPValidationError'
        sms_inbound_mt:
          '{$callback_url}':
            post:
              summary: Sms Inbound Mt
              operationId: sms_inbound_mt__callback_url__post
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/SubscriptionSMSEvent'
              responses:
                '200':
                  description: Successful Response
                  content:
                    application/json:
                      schema: {}
                '422':
                  description: Validation Error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/HTTPValidationError'
        sms_delivery_status:
          '{$callback_url}':
            post:
              summary: Sms Delivery Status
              operationId: sms_delivery_status__callback_url__post
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/PremiumSMSDeliveryStatusEvent'
              responses:
                '200':
                  description: Successful Response
                  content:
                    application/json:
                      schema: {}
                '422':
                  description: Validation Error
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/HTTPValidationError'
      security:
        - X-API-Key: []
components:
  schemas:
    ActorType:
      title: ActorType
      enum:
        - system
        - user
      type: string
      description: An enumeration.
    BulkSMSDeliveryStatusEvent:
      title: BulkSMSDeliveryStatusEvent
      required:
        - uid
        - actor_type
        - event_type
        - created_at
        - data
      type: object
      properties:
        uid:
          title: Uid
          type: string
        actor_type:
          $ref: '#/components/schemas/ActorType'
        event_type:
          $ref: '#/components/schemas/EventType'
        created_at:
          title: Created At
          type: string
        data:
          $ref: '#/components/schemas/SMSDeliveryStatus'
      example:
        uid: 45$045ea8b3abf540aa89cac71985b3a278
        actor_type: system
        event_type: sms_delivery_status
        created_at: '1594868435'
        data:
          message_id: abf540aa89cac71985b3a278
          message_ref: 76387871a0bd4f44afcbf3af8fb53054
          status: delivered
          status_reason: delivered_to_terminal
          status_description: Message Delivered to the User's mobile device
    BulkSMSMessage:
      title: BulkSMSMessage
      required:
        - mobile_number
        - message
        - message_type
      type: object
      properties:
        mobile_number:
          title: Mobile Number
          maxLength: 12
          minLength: 12
          pattern: ^2547\d{8}$|2541\d{8}$
          type: string
          example: 2547XXXXXXXX
        message:
          title: Text Message
          maxLength: 785
          minLength: 1
          type: string
          description: Message to send to recipient(s)
          example: Hello, It works!
        message_type:
          title: Message Type
          allOf:
            - $ref: '#/components/schemas/BulkSMSMessageType'
        message_ref:
          title: Message Unique Reference
          maxLength: 50
          type: string
          description: To be provided by external services
          example: 76387871a0bd4f44afcbf3af8fb53054
    BulkSMSMessageType:
      title: BulkSMSMessageType
      enum:
        - promotional
        - transactional
      type: string
      description: An enumeration.
    BulkSMSRequest:
      title: BulkSMSRequest
      required:
        - profile_code
        - messages
      type: object
      properties:
        profile_code:
          title: Profile Code
          pattern: \d+
          type: string
          description: Linked to specific sms product configuration
          example: '12345'
        messages:
          title: Messages
          maxItems: 20
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/BulkSMSMessage'
        dlr_callback_url:
          title: Dlr Callback Url
          maxLength: 2083
          minLength: 1
          type: string
          format: uri
    BulkSMSResponse:
      title: BulkSMSResponse
      required:
        - message_id
        - mobile_number
        - sms_count
      type: object
      properties:
        message_id:
          title: Message Id
          type: string
        message_ref:
          title: Message Ref
          type: string
        mobile_number:
          title: Mobile Number
          type: string
        sms_count:
          title: Sms Count
          type: integer
      example:
        message_id: abf540aa89cac71985b3a278
        message_ref: 76387871a0bd4f44afcbf3af8fb53054
        mobile_number: 2547XXXXXXXX
    EventType:
      title: EventType
      enum:
        - sms_delivery_status
        - sms_mo_inbound
        - sms_mt_inbound
      type: string
      description: An enumeration.
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    MobileOriginatedSMSData:
      title: MobileOriginatedSMSData
      required:
        - profile_code
        - mobile_number
        - link_id
        - message
      type: object
      properties:
        profile_code:
          title: Profile Code
          pattern: \d+
          type: string
          description: Linked to specific sms product configuration
          example: '12345'
        mobile_number:
          title: Mobile Number
          maxLength: 12
          minLength: 12
          pattern: ^2547\d{8}$|2541\d{8}$
          type: string
          example: 2547XXXXXXXX
        link_id:
          title: Link Id
          type: string
        message:
          title: Message
          type: string
    MobileOriginatedSMSEvent:
      title: MobileOriginatedSMSEvent
      required:
        - uid
        - created_at
        - data
      type: object
      properties:
        uid:
          title: Uid
          type: string
        actor_type:
          allOf:
            - $ref: '#/components/schemas/ActorType'
          default: user
        event_type:
          allOf:
            - $ref: '#/components/schemas/EventType'
          default: sms_mo_inbound
        created_at:
          title: Created At
          type: string
        data:
          $ref: '#/components/schemas/MobileOriginatedSMSData'
    PremiumSMSDeliveryStatusEvent:
      title: PremiumSMSDeliveryStatusEvent
      required:
        - uid
        - actor_type
        - event_type
        - created_at
        - data
      type: object
      properties:
        uid:
          title: Uid
          type: string
        actor_type:
          $ref: '#/components/schemas/ActorType'
        event_type:
          $ref: '#/components/schemas/EventType'
        created_at:
          title: Created At
          type: string
        data:
          $ref: '#/components/schemas/SMSDeliveryStatus'
      example:
        uid: 45$045ea8b3abf540aa89cac71985b3a278
        actor_type: system
        event_type: sms_delivery_status
        created_at: '1594868435'
        data:
          message_id: abf540aa89cac71985b3a278
          message_ref: 76387871a0bd4f44afcbf3af8fb53054
          status: delivered
          status_reason: delivered_to_terminal
          status_description: Message Delivered to the User's mobile device
    PremiumSMSMessage:
      title: PremiumSMSMessage
      required:
        - mobile_number
        - message
      type: object
      properties:
        mobile_number:
          title: Mobile Number
          maxLength: 12
          minLength: 12
          pattern: ^2547\d{8}$|2541\d{8}$
          type: string
          example: 2547XXXXXXXX
        message:
          title: Text Message
          maxLength: 10000
          minLength: 1
          type: string
          description: Message to send to recipient(s)
          example: Hello, It works!
        message_ref:
          title: Message Unique Reference
          maxLength: 50
          type: string
          description: To be provided by external services
          example: 76387871a0bd4f44afcbf3af8fb53054
        link_id:
          title: Link ID
          maxLength: 100
          type: string
          description: Link ID Received for MO Inbound SMS
          example: '12340000'
    PremiumSMSRequest:
      title: PremiumSMSRequest
      required:
        - profile_code
        - messages
      type: object
      properties:
        profile_code:
          title: Profile Code
          pattern: \d+
          type: string
          description: Linked to specific sms product configuration
          example: '12345'
        messages:
          title: Messages
          maxItems: 5
          minItems: 1
          type: array
          items:
            $ref: '#/components/schemas/PremiumSMSMessage'
        dlr_callback_url:
          title: Dlr Callback Url
          maxLength: 2083
          minLength: 1
          type: string
          format: uri
    PremiumSMSResponse:
      title: PremiumSMSResponse
      required:
        - message_id
        - mobile_number
      type: object
      properties:
        message_id:
          title: Message Id
          type: string
        message_ref:
          title: Message Ref
          type: string
        mobile_number:
          title: Mobile Number
          type: string
      example:
        message_id: abf540aa89cac71985b3a278
        message_ref: 76387871a0bd4f44afcbf3af8fb53054
        mobile_number: 2547XXXXXXXX
    PremiumSMSSubscriptionRequest:
      title: PremiumSMSSubscriptionRequest
      required:
        - profile_code
        - mobile_number
      type: object
      properties:
        profile_code:
          title: Profile Code
          pattern: \d+
          type: string
          description: Linked to specific sms product configuration
          example: '12345'
        mobile_number:
          title: Mobile Number
          maxLength: 12
          minLength: 12
          pattern: ^2547\d{8}$|2541\d{8}$
          type: string
          example: 2547XXXXXXXX
    PremiumSMSSubscriptionResponse:
      title: PremiumSMSSubscriptionResponse
      required:
        - status
      type: object
      properties:
        status:
          title: Status
          type: string
    PremiumSMSUnSubscriptionResponse:
      title: PremiumSMSUnSubscriptionResponse
      required:
        - status
      type: object
      properties:
        status:
          title: Status
          type: string
    RequestError:
      title: RequestError
      type: object
      properties:
        code:
          title: Code
          type: string
        description:
          title: Description
          type: string
        detail:
          title: Detail
          anyOf:
            - type: string
            - type: object
            - type: array
              items:
                type: object
    SMSDeliveryStatus:
      title: SMSDeliveryStatus
      required:
        - status
        - status_reason
        - message_id
      type: object
      properties:
        status:
          title: Delivery Status
          allOf:
            - $ref: '#/components/schemas/SMSStatus'
          description: The State of the SMS Message
        status_reason:
          title: Status Reason
          allOf:
            - $ref: '#/components/schemas/SMSStatusReason'
          description: Explanation on why the delivery status
        status_description:
          title: Status Reason
          type: string
          description: Detailed information on the delivery status
          example: Message Delivered to the User's mobile device
        message_ref:
          title: Message Ref
          type: string
        message_id:
          title: Message Id
          type: string
    SMSStatus:
      title: SMSStatus
      enum:
        - queued
        - sent
        - delivered
        - undelivered
        - failed
      type: string
      description: An enumeration.
    SMSStatusReason:
      title: SMSStatusReason
      enum:
        - delivered_to_terminal
        - user_in_blacklist
      type: string
      description: An enumeration.
    SubscriptionOperationType:
      title: SubscriptionOperationType
      enum:
        - start
        - stop
      type: string
      description: An enumeration.
    SubscriptionSMSData:
      title: SubscriptionSMSData
      required:
        - profile_code
        - mobile_number
        - operation
      type: object
      properties:
        profile_code:
          title: Profile Code
          pattern: \d+
          type: string
          description: Linked to specific sms product configuration
          example: '12345'
        mobile_number:
          title: Mobile Number
          maxLength: 12
          minLength: 12
          pattern: ^2547\d{8}$|2541\d{8}$
          type: string
          example: 2547XXXXXXXX
        operation:
          $ref: '#/components/schemas/SubscriptionOperationType'
    SubscriptionSMSEvent:
      title: SubscriptionSMSEvent
      required:
        - uid
        - created_at
        - data
      type: object
      properties:
        uid:
          title: Uid
          type: string
        actor_type:
          allOf:
            - $ref: '#/components/schemas/ActorType'
          default: user
        event_type:
          allOf:
            - $ref: '#/components/schemas/EventType'
          default: sms_mt_inbound
        created_at:
          title: Created At
          type: string
        data:
          $ref: '#/components/schemas/SubscriptionSMSData'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            type: string
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
  securitySchemes:
    X-API-Key:
      type: apiKey
      in: header
      name: X-API-Key
